config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:show]
  resources :answers, only: [:create]
  resources :question_sets, only: [:index]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/possible_value.rb
# A PossibleValue represents a logic branch.  If the question system is a graph,
# this is an edge.  It contains the logic like "If user answers 'yes', go to
# question 7."  A question will have one or more of these so the system knows
# where to go next after a user answers it.
class PossibleValue < ActiveRecord::Base

  # Does this PossibleValue cover the answer provided?
  def matches?(answer)
    # TODO: replace this with single table inheritence and just subclass this class
    case format
    when 'option'
      answer.value == value
    when 'range'
      range = JSON.parse(value)
      answer_value = answer.value.to_i
      answer_value >= range[:min].to_i and answer_value <= range[:max].to_i
    when 'anything'
      true
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :possible_values

  accepts_nested_attributes_for :possible_values

  # Given that answer, where should we go next?  Nil if nowhere.
  def next_question( answer )
    found_value = possible_values.find do |possible_value|
      possible_value.matches? answer
    end

    if found_value
      Question.find_by_slug(found_value.next_question_slug)
    else
      # We must be at a 'leaf' on the question tree- a termination point.
      # For now, just return nil.
      # TODO: Return a code, like "ended_because_reason_x" so the calling code
      # knows where to go from here.
    end
  end
end

app/models/question_set.rb
class QuestionSet < ActiveRecord::Base
  belongs_to :head_question, class: Question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    answer = Answer.create!(params.require(:answer).permit!)
    question = answer.question
    next_question = question.next_question(answer)

    if next_question
      redirect_to next_question
    else
      render text: "Quesiton #{question.slug} was the last one."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/question_sets_controller.rb
class QuestionSetsController < ApplicationController
  def index
    @question_sets = QuestionSet.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new(question: @question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionPOC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/question_sets/index.html.erb
<h1>Listing Question Sets</h1>

<table>
  <thead>
    <tr>
      <th>slug</th>
    </tr>
  </thead>

  <tbody>
    <% @question_sets.each do |question_set| %>
      <tr>
        <td><%= question_set.slug %></td>
        <td><%= link_to 'Start', question_set.head_question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/questions/_form_dropdown.html.erb
<%= form_for @answer do |f| %>
  <%= f.hidden_field :question_id, value: @answer.question.id %>
  <p>
    <%= f.select :value, options_for_select(JSON.parse(@question.options_json)) %>
  </p>
  <input type='submit' />
<% end %>

app/views/questions/_form_text.html.erb
<%= form_for @answer do |f| %>
  <%= f.hidden_field :question_id, value: @answer.question.id %>
  <p>
    <%= f.text_area :value %>
  </p>
  <input type='submit' />
<% end %>

app/views/questions/_form_true_false.html.erb
<%= form_for @answer do |f| %>
  <%= f.hidden_field :question_id, value: @answer.question.id %>
  <p>
    <%= f.radio_button :value, 'true' %>true
    <%= f.radio_button :value, 'false' %>false
  </p>
  <input type='submit' />
<% end %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>format</th>
      <th>Prompt</th>
      <th>Instructions</th>
      <th>Focus</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.format %></td>
        <td><%= question.prompt %></td>
        <td><%= question.instructions %></td>
        <td><%= question.focus %></td>
        <td><%= question.slug %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prompt:</strong>
  <%= @question.prompt %>
</p>

<%= render 'form_' + @question.format %>